In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.zeros((50000,2))
s = pd.Series(list(a))

In [3]:
%timeit (np.vstack(s.values))

29.8 ms ± 54.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
 %timeit (np.array(s.values.tolist()))

9.41 ms ± 60.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit (np.array(s.tolist()))

9.39 ms ± 25.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
d1=np.vstack(s.values)
print(type(d1))

<class 'numpy.ndarray'>


In [7]:
d1.shape

(50000, 2)

In [9]:
print(d1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
dat=d1.flatten()

In [13]:
print(len(dat))

100000


In [14]:
print(dat)

[0. 0. 0. ... 0. 0. 0.]


In [15]:
dat.reshape(250,200,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       ...,

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]])